apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea-operator
  template:
    metadata:
      labels:
        name: gitea-operator
    spec:
      serviceAccountName: gitea-operator
      containers:
        - name: gitea-operator
          # Replace this with the built image name
          image: quay.io/paulwelch/gitea-operator
          command:
          - gitea-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitea-operator"
